pipeline:
  name: Build and Sign Container Image
  identifier: Build_and_Sign_Container_Image
  projectIdentifier: demossk
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.SKGitHub
        repoName: cosign-examples
        build: <+input>
  stages:
    - stage:
        name: Get Sign Token
        identifier: Get_Sign_Token
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: tokens
                  identifier: tokens
                  spec:
                    connectorRef: account.Pratyakshika
                    image: asia.gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
                    shell: Bash
                    command: |-
                      echo -n "$GOOGLE_APPLICATION_CREDENTIALS" > "$HOME/.ssh/sa.json"
                      gcloud auth activate-service-account --project="$PROJECT_ID" --key-file="$HOME/.ssh/sa.json" ""$SA_NAME"
                      gcloud auth print-identity-token \
                        --audiences=sigstore  \
                        --include-email \
                        --impersonate-service-account "$SA_NAME"
                    envVariables:
                      SA_NAME: sk-devrel@pratyakshika.iam.gserviceaccount.com
                      PROJECT_ID: pratyakshika
                      GOOGLE_APPLICATION_CREDENTIALS: <+secrets.getValue("account.SAskdevrel")>
                    imagePullPolicy: IfNotPresent
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
