kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
  - name: configure gcloud
    image: docker.io/kameshsampath/drone-gcloud-auth:2.0.0
    pull: if-not-exists
    settings:
      google_application_credentials:
        from_secret: google_application_credentials
      google_cloud_project:
        from_secret: google_cloud_project
      registry_locations:
        - asia-south1
    volumes:
      - name: gcloud-config
        path: /root/.config/gcloud
  - name: create docker repository
    image: docker.io/kameshsampath/drone-gcloud-auth:2.0.0
    commands:
     - scripts/repo.sh
    volumes:
      - name: gcloud-config
        path: /root/.config/gcloud
  - name: get access and id token
    image: docker.io/kameshsampath/drone-gcloud-auth:2.0.0
    commands:
      - scripts/tokens.sh
    volumes:
      - name: gcloud-config
        path: /root/.config/gcloud
      - name: id-token
        path: /root/images
  - name: build and push
    image: kameshsampath/kube-dev-tools:0.1.4
    commands:
     - scripts/build-push.sh
    volumes:
      - name: gcloud-config
        path: /root/.config/gcloud
      - name: id-token
        path: /root/images
volumes:
  - name: gcloud-config
    temp: {}
  - name: id-token
    temp: {}
